In [1]:
import yfinance as yf

datos = yf.download("GC=F", period="1y", interval="1d")
datos.head()

[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open Volume
Ticker             GC=F         GC=F         GC=F         GC=F   GC=F
Date
2025-08-05  3381.899902  3387.199951  3351.199951  3378.500000    915
2025-08-06  3380.000000  3383.300049  3361.300049  3380.699951   1492
2025-08-07  3400.300049  3422.899902  3384.899902  3384.899902   5464
2025-08-08  3439.100098  3477.000000  3402.500000  3438.800049   7657
2025-08-11  3353.100098  3383.899902  3349.199951  3383.899902   1488

In [2]:
print(f"Total de días descargados: {len(datos)}")
print(f"Desde: {datos.index.min()} hasta: {datos.index.max()}")

Total de días descargados: 252
Desde: 2025-08-05 00:00:00 hasta: 2026-08-05 00:00:00

In [3]:
print(datos.columns)

MultiIndex([( 'Close', 'GC=F'),
            (  'High', 'GC=F'),
            (   'Low', 'GC=F'),
            (  'Open', 'GC=F'),
            ('Volume', 'GC=F')],
           names=['Price', 'Ticker'])

In [4]:
datos = datos[["Open", "High", "Low", "Close", "Volume"]]
datos.head()

Price              Open         High          Low        Close Volume
Ticker             GC=F         GC=F         GC=F         GC=F   GC=F
Date
2025-08-05  3378.500000  3387.199951  3351.199951  3381.899902    915
2025-08-06  3380.699951  3383.300049  3361.300049  3380.000000   1492
2025-08-07  3384.899902  3422.899902  3384.899902  3400.300049   5464
2025-08-08  3438.800049  3477.000000  3402.500000  3439.100098   7657
2025-08-11  3383.899902  3383.899902  3349.199951  3353.100098   1488

In [5]:
datos.to_csv("../data/XAUUSD_diario.csv")
print("Datos guardados correctamente")

Datos guardados correctamente

In [6]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Candlestick(
    x=datos.index,
    open=datos["Open"],
    high=datos["High"],
    low=datos["Low"],
    close=datos["Close"]
)])

fig.update_layout(title="XAUUSD - Velas Diarias (1 año)", xaxis_title="Fecha", yaxis_title="Precio (USD)")
fig.show()

In [7]:
print(datos.columns)
print(type(datos["Open"]))

MultiIndex([(  'Open', 'GC=F'),
            (  'High', 'GC=F'),
            (   'Low', 'GC=F'),
            ( 'Close', 'GC=F'),
            ('Volume', 'GC=F')],
           names=['Price', 'Ticker'])
<class 'pandas.DataFrame'>

In [8]:
datos.columns = datos.columns.get_level_values(0)
print(datos.columns)

Index(['Open', 'High', 'Low', 'Close', 'Volume'], dtype='str', name='Price')

In [9]:
import pandas as pd
verificacion = pd.read_csv("../data/XAUUSD_diario.csv")
print(verificacion.columns)

Index(['Price', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='str')

In [10]:
print(verificacion.head())

        Price               Open               High                Low  \
0      Ticker               GC=F               GC=F               GC=F
1        Date                NaN                NaN                NaN
2  2025-08-05             3378.5  3387.199951171875  3351.199951171875
3  2025-08-06  3380.699951171875  3383.300048828125  3361.300048828125
4  2025-08-07   3384.89990234375   3422.89990234375   3384.89990234375

               Close Volume
0               GC=F   GC=F
1                NaN    NaN
2   3381.89990234375    915
3             3380.0   1492
4  3400.300048828125   5464

In [11]:
print(datos.columns)

Index(['Open', 'High', 'Low', 'Close', 'Volume'], dtype='str', name='Price')

In [12]:
datos.columns.name = None
print(datos.columns)

Index(['Open', 'High', 'Low', 'Close', 'Volume'], dtype='str')

In [13]:
datos.to_csv("../data/XAUUSD_diario.csv")
print("CSV regenerado correctamente")

CSV regenerado correctamente

In [14]:
verificacion = pd.read_csv("../data/XAUUSD_diario.csv")
print(verificacion.head())

         Date         Open         High          Low        Close  Volume
0  2025-08-05  3378.500000  3387.199951  3351.199951  3381.899902     915
1  2025-08-06  3380.699951  3383.300049  3361.300049  3380.000000    1492
2  2025-08-07  3384.899902  3422.899902  3384.899902  3400.300049    5464
3  2025-08-08  3438.800049  3477.000000  3402.500000  3439.100098    7657
4  2025-08-11  3383.899902  3383.899902  3349.199951  3353.100098    1488