In [ ]:
import yfinance as yf

datos = yf.download("GC=F", period="1y", interval="1d")git add .
datos.head()

[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open Volume
Ticker             GC=F         GC=F         GC=F         GC=F   GC=F
Date
2025-08-04  3374.399902  3386.500000  3347.399902  3367.600098    351
2025-08-05  3381.899902  3387.199951  3351.199951  3378.500000    915
2025-08-06  3380.000000  3383.300049  3361.300049  3380.699951   1492
2025-08-07  3400.300049  3422.899902  3384.899902  3384.899902   5464
2025-08-08  3439.100098  3477.000000  3402.500000  3438.800049   7657

In [2]:
print(f"Total de días descargados: {len(datos)}")
print(f"Desde: {datos.index.min()} hasta: {datos.index.max()}")

Total de días descargados: 251
Desde: 2025-08-04 00:00:00 hasta: 2026-08-03 00:00:00

In [3]:
print(datos.columns)

MultiIndex([( 'Close', 'GC=F'),
            (  'High', 'GC=F'),
            (   'Low', 'GC=F'),
            (  'Open', 'GC=F'),
            ('Volume', 'GC=F')],
           names=['Price', 'Ticker'])

In [4]:
datos = datos[["Open", "High", "Low", "Close", "Volume"]]
datos.head()

Price              Open         High          Low        Close Volume
Ticker             GC=F         GC=F         GC=F         GC=F   GC=F
Date
2025-08-04  3367.600098  3386.500000  3347.399902  3374.399902    351
2025-08-05  3378.500000  3387.199951  3351.199951  3381.899902    915
2025-08-06  3380.699951  3383.300049  3361.300049  3380.000000   1492
2025-08-07  3384.899902  3422.899902  3384.899902  3400.300049   5464
2025-08-08  3438.800049  3477.000000  3402.500000  3439.100098   7657

In [5]:
datos.to_csv("../data/XAUUSD_diario.csv")
print("Datos guardados correctamente")

Datos guardados correctamente

In [12]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Candlestick(
    x=datos.index,
    open=datos["Open"],
    high=datos["High"],
    low=datos["Low"],
    close=datos["Close"]
)])

fig.update_layout(title="XAUUSD - Velas Diarias (1 año)", xaxis_title="Fecha", yaxis_title="Precio (USD)")
fig.show()

In [9]:
print(datos.columns)
print(type(datos["Open"]))

MultiIndex([(  'Open', 'GC=F'),
            (  'High', 'GC=F'),
            (   'Low', 'GC=F'),
            ( 'Close', 'GC=F'),
            ('Volume', 'GC=F')],
           names=['Price', 'Ticker'])
<class 'pandas.DataFrame'>

In [ ]:
datos.columns = datos.columns.get_level_values(0)
print(datos.columns)

Index(['Open', 'High', 'Low', 'Close', 'Volume'], dtype='str', name='Price')