In [1]:
import pandas as pd

datos = pd.read_csv("../data/XAUUSD_diario.csv", index_col="Date", parse_dates=True)
datos.head()

                   Open         High          Low        Close  Volume
Date
2025-08-05  3378.500000  3387.199951  3351.199951  3381.899902     915
2025-08-06  3380.699951  3383.300049  3361.300049  3380.000000    1492
2025-08-07  3384.899902  3422.899902  3384.899902  3400.300049    5464
2025-08-08  3438.800049  3477.000000  3402.500000  3439.100098    7657
2025-08-11  3383.899902  3383.899902  3349.199951  3353.100098    1488

In [2]:
print(datos.dtypes)

Open      float64
High      float64
Low       float64
Close     float64
Volume      int64
dtype: object

In [3]:
print(datos.index.dtype)

datetime64[us]

In [4]:
datos["MA_rapida"] = datos["Close"].rolling(window=20).mean()
datos["MA_lenta"] = datos["Close"].rolling(window=50).mean()

datos[["Close", "MA_rapida", "MA_lenta"]].tail(10)

                  Close    MA_rapida     MA_lenta
Date
2026-07-23  4046.600098  4065.835022  4267.036001
2026-07-24  4067.600098  4067.690027  4254.836001
2026-07-27  4074.500000  4067.480029  4242.371997
2026-07-28  4036.300049  4068.180029  4229.535996
2026-07-29  4034.699951  4068.770032  4219.113999
2026-07-30  4100.100098  4070.360034  4210.066001
2026-07-31  4049.100098  4067.180029  4200.922007
2026-08-03  4033.699951  4061.110022  4190.970010
2026-08-04  4095.399902  4058.615027  4182.082012
2026-08-05  4321.299805  4071.135022  4178.088008

In [5]:
datos["Señal"] = 0
datos.loc[datos["MA_rapida"] > datos["MA_lenta"], "Señal"] = 1
datos.loc[datos["MA_rapida"] < datos["MA_lenta"], "Señal"] = -1

datos[["Close", "MA_rapida", "MA_lenta", "Señal"]].tail(10)

                  Close    MA_rapida     MA_lenta  Señal
Date
2026-07-23  4046.600098  4065.835022  4267.036001     -1
2026-07-24  4067.600098  4067.690027  4254.836001     -1
2026-07-27  4074.500000  4067.480029  4242.371997     -1
2026-07-28  4036.300049  4068.180029  4229.535996     -1
2026-07-29  4034.699951  4068.770032  4219.113999     -1
2026-07-30  4100.100098  4070.360034  4210.066001     -1
2026-07-31  4049.100098  4067.180029  4200.922007     -1
2026-08-03  4033.699951  4061.110022  4190.970010     -1
2026-08-04  4095.399902  4058.615027  4182.082012     -1
2026-08-05  4321.299805  4071.135022  4178.088008     -1

In [6]:
datos["Cambio"] = datos["Señal"].diff()

datos[datos["Cambio"] != 0][["Close", "MA_rapida", "MA_lenta", "Señal", "Cambio"]]

                  Close    MA_rapida     MA_lenta  Señal  Cambio
Date
2025-08-05  3381.899902          NaN          NaN      0     NaN
2025-10-14  4138.700195  3857.510022  3623.193999      1     1.0
2026-03-26  4375.500000  4920.274976  4943.711973     -1    -2.0

In [7]:
datos[["Close", "MA_rapida", "MA_lenta", "Señal"]].head(55)

                  Close    MA_rapida     MA_lenta  Señal
Date
2025-08-05  3381.899902          NaN          NaN      0
2025-08-06  3380.000000          NaN          NaN      0
2025-08-07  3400.300049          NaN          NaN      0
2025-08-08  3439.100098          NaN          NaN      0
2025-08-11  3353.100098          NaN          NaN      0
2025-08-12  3348.899902          NaN          NaN      0
2025-08-13  3358.699951          NaN          NaN      0
2025-08-14  3335.199951          NaN          NaN      0
2025-08-15  3336.000000          NaN          NaN      0
2025-08-18  3331.699951          NaN          NaN      0
2025-08-19  3313.399902          NaN          NaN      0
2025-08-20  3343.399902          NaN          NaN      0
2025-08-21  3336.899902          NaN          NaN      0
2025-08-22  3374.399902          NaN          NaN      0
2025-08-25  3373.800049          NaN          NaN      0
2025-08-26  3388.600098          NaN          NaN      0
2025-08-27  3404.600098          NaN          NaN      0
2025-08-28  3431.800049          NaN          NaN      0
2025-08-29  3473.699951          NaN          NaN      0
2025-09-02  3549.399902  3382.744983          NaN      0
2025-09-03  3593.199951  3393.309985          NaN      0
2025-09-04  3565.800049  3402.599988          NaN      0
2025-09-05  3613.199951  3413.244983          NaN      0
2025-09-08  3638.100098  3423.194983          NaN      0
2025-09-09  3643.300049  3437.704980          NaN      0
2025-09-10  3643.600098  3452.439990          NaN      0
2025-09-11  3636.899902  3466.349988          NaN      0
2025-09-12  3649.399902  3482.059985          NaN      0
2025-09-15  3682.199951  3499.369983          NaN      0
2025-09-16  3688.899902  3517.229980          NaN      0
2025-09-17  3681.800049  3535.649988          NaN      0
2025-09-18  3643.699951  3550.664990          NaN      0
2025-09-19  3671.500000  3567.394995          NaN      0
2025-09-22  3740.699951  3585.709998          NaN      0
2025-09-23  3780.600098  3606.050000          NaN      0
2025-09-24  3732.100098  3623.225000          NaN      0
2025-09-25  3736.899902  3639.839990          NaN      0
2025-09-26  3775.300049  3657.014990          NaN      0
2025-09-29  3820.899902  3674.374988          NaN      0
2025-09-30  3840.800049  3688.944995          NaN      0
2025-10-01  3867.500000  3702.659998          NaN      0
2025-10-02  3839.699951  3716.354993          NaN      0
2025-10-03  3880.800049  3729.734998          NaN      0
2025-10-06  3948.500000  3745.254993          NaN      0
2025-10-07  3976.600098  3761.919995          NaN      0
2025-10-08  4043.300049  3781.904993          NaN      0
2025-10-09  3946.300049  3797.375000          NaN      0
2025-10-10  3975.899902  3813.700000          NaN      0
2025-10-13  4108.600098  3835.020007          NaN      0
2025-10-14  4138.700195  3857.510022  3623.193999      1
2025-10-15  4176.899902  3882.265015  3639.093999      1
2025-10-16  4280.200195  3914.090027  3657.098003      1
2025-10-17  4189.899902  3940.010022  3672.890000      1
2025-10-20  4336.399902  3969.795020  3690.835996      1
2025-10-21  4087.699951  3985.150012  3705.527993      1

In [8]:
datos["Retorno_diario"] = datos["Close"].pct_change()

datos["Retorno_estrategia"] = datos["Señal"].shift(1) * datos["Retorno_diario"]

datos[["Close", "Señal", "Retorno_diario", "Retorno_estrategia"]].tail(10)

                  Close  Señal  Retorno_diario  Retorno_estrategia
Date
2026-07-23  4046.600098     -1       -0.024187            0.024187
2026-07-24  4067.600098     -1        0.005190           -0.005190
2026-07-27  4074.500000     -1        0.001696           -0.001696
2026-07-28  4036.300049     -1       -0.009375            0.009375
2026-07-29  4034.699951     -1       -0.000396            0.000396
2026-07-30  4100.100098     -1        0.016209           -0.016209
2026-07-31  4049.100098     -1       -0.012439            0.012439
2026-08-03  4033.699951     -1       -0.003803            0.003803
2026-08-04  4095.399902     -1        0.015296           -0.015296
2026-08-05  4321.299805     -1        0.055159           -0.055159

In [9]:
datos["Retorno_acumulado"] = (1 + datos["Retorno_estrategia"]).cumprod()

datos[["Close", "Retorno_estrategia", "Retorno_acumulado"]].tail(10)

                  Close  Retorno_estrategia  Retorno_acumulado
Date
2026-07-23  4046.600098            0.024187           1.121106
2026-07-24  4067.600098           -0.005190           1.115288
2026-07-27  4074.500000           -0.001696           1.113396
2026-07-28  4036.300049            0.009375           1.123834
2026-07-29  4034.699951            0.000396           1.124280
2026-07-30  4100.100098           -0.016209           1.106056
2026-07-31  4049.100098            0.012439           1.119814
2026-08-03  4033.699951            0.003803           1.124073
2026-08-04  4095.399902           -0.015296           1.106879
2026-08-05  4321.299805           -0.055159           1.045824

In [10]:
datos["Tramo"] = (datos["Cambio"] != 0).cumsum()

In [11]:
tabla = datos.reset_index()

resumen_tramos = tabla.groupby("Tramo").agg(
    Fecha_inicio=("Date", "min"),
    Fecha_fin=("Date", "max"),
    Dias=("Date", "count"),
    Señal=("Señal", "first"),
    Retorno_total=("Retorno_estrategia", lambda x: (1 + x).prod() - 1)
)

resumen_tramos

      Fecha_inicio  Fecha_fin  Dias  Señal  Retorno_total
Tramo
1       2025-08-05 2025-10-13    49      0       0.000000
2       2025-10-14 2026-03-25   112      1       0.099331
3       2026-03-26 2026-08-05    91     -1      -0.048672

In [12]:
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter(x=datos.index, y=datos["Retorno_acumulado"], mode="lines", name="Estrategia"))

fig.update_layout(title="Curva de Capital - Estrategia Cruce de Medias (XAUUSD)",
                   xaxis_title="Fecha", yaxis_title="Capital (base $1)")
fig.show()

In [13]:
datos["Maximo_historico"] = datos["Retorno_acumulado"].cummax()
datos["Drawdown"] = (datos["Retorno_acumulado"] / datos["Maximo_historico"]) - 1

drawdown_maximo = datos["Drawdown"].min()
print(f"Drawdown máximo: {drawdown_maximo:.2%}")

Drawdown máximo: -26.20%

In [14]:
operaciones = resumen_tramos[resumen_tramos["Señal"] != 0]

ganadoras = operaciones[operaciones["Retorno_total"] > 0]

win_rate = len(ganadoras) / len(operaciones)
print(f"Total de operaciones: {len(operaciones)}")
print(f"Operaciones ganadoras: {len(ganadoras)}")
print(f"Win rate: {win_rate:.2%}")

Total de operaciones: 2
Operaciones ganadoras: 1
Win rate: 50.00%

In [15]:
retorno_promedio_diario = datos["Retorno_estrategia"].mean()
volatilidad_diaria = datos["Retorno_estrategia"].std()

sharpe_ratio = (retorno_promedio_diario / volatilidad_diaria) * (252 ** 0.5)

print(f"Retorno promedio diario: {retorno_promedio_diario:.4%}")
print(f"Volatilidad diaria: {volatilidad_diaria:.4%}")
print(f"Sharpe Ratio (anualizado): {sharpe_ratio:.2f}")

Retorno promedio diario: 0.0333%
Volatilidad diaria: 1.7452%
Sharpe Ratio (anualizado): 0.30

In [16]:
import sys
sys.path.append("..")

from src.strategies.cruce_medias import cruce_medias
from src.backtesting.metricas import calcular_metricas

datos_prueba = pd.read_csv("../data/XAUUSD_diario.csv", index_col="Date", parse_dates=True)
datos_prueba = cruce_medias(datos_prueba)

print(datos_prueba[["Close", "MA_rapida", "MA_lenta", "Señal"]].tail())

                  Close    MA_rapida     MA_lenta  Señal
Date
2026-07-30  4100.100098  4070.360034  4210.066001     -1
2026-07-31  4049.100098  4067.180029  4200.922007     -1
2026-08-03  4033.699951  4061.110022  4190.970010     -1
2026-08-04  4095.399902  4058.615027  4182.082012     -1
2026-08-05  4321.299805  4071.135022  4178.088008     -1