In [1]:
import yfinance as yf

datos_h1 = yf.download("GC=F", period="730d", interval="1h")
datos_h1.head()

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,GC=F,GC=F,GC=F,GC=F,GC=F
Datetime,,,,,
2024-03-20 00:00:00-04:00,2159.800049,2163.300049,2159.800049,2163.000000,0
2024-03-20 01:00:00-04:00,2160.399902,2161.199951,2159.500000,2159.899902,1582
2024-03-20 02:00:00-04:00,2159.800049,2161.100098,2159.199951,2160.300049,3279
2024-03-20 03:00:00-04:00,2161.000000,2162.399902,2159.699951,2159.899902,3805
2024-03-20 04:00:00-04:00,2158.899902,2161.199951,2157.300049,2160.899902,6001

In [2]:
datos_h1.columns = datos_h1.columns.get_level_values(0)
datos_h1.columns.name = None
datos_h1 = datos_h1[["Open", "High", "Low", "Close", "Volume"]]

datos_h1.head()

,Open,High,Low,Close,Volume
Datetime,,,,,
2024-03-20 00:00:00-04:00,2163.000000,2163.300049,2159.800049,2159.800049,0
2024-03-20 01:00:00-04:00,2159.899902,2161.199951,2159.500000,2160.399902,1582
2024-03-20 02:00:00-04:00,2160.300049,2161.100098,2159.199951,2159.800049,3279
2024-03-20 03:00:00-04:00,2159.899902,2162.399902,2159.699951,2161.000000,3805
2024-03-20 04:00:00-04:00,2160.899902,2161.199951,2157.300049,2158.899902,6001

In [3]:
datos_h1.to_csv("../data/XAUUSD_h1.csv")
print("Datos H1 guardados correctamente")

Datos H1 guardados correctamente

In [4]:
datos_h4 = datos_h1.resample("4h", offset="17h").agg({
    "Open": "first",
    "High": "max",
    "Low": "min",
    "Close": "last",
    "Volume": "sum"
})

datos_h4 = datos_h4.dropna()

datos_h4.head()

,Open,High,Low,Close,Volume
Datetime,,,,,
2024-03-19 21:00:00-04:00,2163.000000,2163.300049,2159.800049,2159.800049,0
2024-03-20 01:00:00-04:00,2159.899902,2162.399902,2157.300049,2158.899902,14667
2024-03-20 05:00:00-04:00,2158.899902,2159.000000,2152.300049,2155.899902,37230
2024-03-20 09:00:00-04:00,2156.000000,2168.199951,2153.199951,2160.899902,59900
2024-03-20 13:00:00-04:00,2160.800049,2192.199951,2159.800049,2189.600098,99347

In [5]:
datos_h12 = datos_h1.resample("12h", offset="17h").agg({
    "Open": "first",
    "High": "max",
    "Low": "min",
    "Close": "last",
    "Volume": "sum"
})

datos_h12 = datos_h12.dropna()

datos_h12.head()

,Open,High,Low,Close,Volume
Datetime,,,,,
2024-03-19 17:00:00-04:00,2163.000000,2163.300049,2157.300049,2158.899902,14667
2024-03-20 05:00:00-04:00,2158.899902,2192.199951,2152.300049,2189.600098,196477
2024-03-20 17:00:00-04:00,2190.199951,2225.300049,2190.000000,2203.500000,73946
2024-03-21 05:00:00-04:00,2203.600098,2214.100098,2168.199951,2183.300049,270175
2024-03-21 17:00:00-04:00,2183.399902,2188.000000,2163.800049,2169.300049,54744

In [7]:
datos_h4.to_csv("../data/XAUUSD_h4.csv")
datos_h12.to_csv("../data/XAUUSD_h12.csv")
print("Velas H4 y H12 guardadas correctamente")

Velas H4 y H12 guardadas correctamente

In [8]:
datos_h12["C1"] = datos_h12["Close"]
datos_h12["C2"] = datos_h12["Close"].shift(1)
datos_h12["C3"] = datos_h12["Close"].shift(2)

datos_h12[["Close", "C1", "C2", "C3"]].head(10)

                                 Close           C1           C2           C3
Datetime
2024-03-19 17:00:00-04:00  2158.899902  2158.899902          NaN          NaN
2024-03-20 05:00:00-04:00  2189.600098  2189.600098  2158.899902          NaN
2024-03-20 17:00:00-04:00  2203.500000  2203.500000  2189.600098  2158.899902
2024-03-21 05:00:00-04:00  2183.300049  2183.300049  2203.500000  2189.600098
2024-03-21 17:00:00-04:00  2169.300049  2169.300049  2183.300049  2203.500000
2024-03-22 05:00:00-04:00  2166.500000  2166.500000  2169.300049  2183.300049
2024-03-24 17:00:00-04:00  2166.699951  2166.699951  2166.500000  2169.300049
2024-03-25 05:00:00-04:00  2173.000000  2173.000000  2166.699951  2166.500000
2024-03-25 17:00:00-04:00  2178.800049  2178.800049  2173.000000  2166.699951
2024-03-26 05:00:00-04:00  2179.500000  2179.500000  2178.800049  2173.000000

In [9]:
datos_h12["Es_roja"] = datos_h12["Close"] < datos_h12["Open"]

datos_h12["OURAS"] = datos_h12["Open"].where(datos_h12["Es_roja"]).ffill()

datos_h12[["Open", "Close", "Es_roja", "OURAS"]].head(15)

                                  Open        Close  Es_roja        OURAS
Datetime
2024-03-19 17:00:00-04:00  2163.000000  2158.899902     True  2163.000000
2024-03-20 05:00:00-04:00  2158.899902  2189.600098    False  2163.000000
2024-03-20 17:00:00-04:00  2190.199951  2203.500000    False  2163.000000
2024-03-21 05:00:00-04:00  2203.600098  2183.300049     True  2203.600098
2024-03-21 17:00:00-04:00  2183.399902  2169.300049     True  2183.399902
2024-03-22 05:00:00-04:00  2169.399902  2166.500000     True  2169.399902
2024-03-24 17:00:00-04:00  2166.600098  2166.699951    False  2169.399902
2024-03-25 05:00:00-04:00  2166.800049  2173.000000    False  2169.399902
2024-03-25 17:00:00-04:00  2173.000000  2178.800049    False  2169.399902
2024-03-26 05:00:00-04:00  2178.800049  2179.500000    False  2169.399902
2024-03-26 17:00:00-04:00  2179.399902  2197.800049    False  2169.399902
2024-03-27 05:00:00-04:00  2197.699951  2215.399902    False  2169.399902
2024-03-27 17:00:00-04:00  2215.699951  2215.100098     True  2215.699951
2024-03-28 05:00:00-04:00  2215.199951  2254.800049    False  2215.699951
2024-03-31 17:00:00-04:00  2259.199951  2277.899902    False  2215.699951

In [10]:
datos_h12.to_csv("../data/XAUUSD_h12_completo.csv")
print("Datos H12 con C1, C2, C3 y OURAS guardados")

Datos H12 con C1, C2, C3 y OURAS guardados

In [11]:
datos_h12["Escenario_A"] = (datos_h12["C1"] > datos_h12["C2"]) & (datos_h12["C1"] > datos_h12["C3"])
datos_h12["Escenario_B"] = (datos_h12["C1"] < datos_h12["C2"]) & (datos_h12["C1"] > datos_h12["C3"])

datos_h12[["C1", "C2", "C3", "Escenario_A", "Escenario_B"]].tail(10)

,C1,C2,C3,Escenario_A,Escenario_B
Datetime,,,,,
2026-08-06 05:00:00-04:00,4298.700195,4337.100098,4308.000000,False,False
2026-08-06 17:00:00-04:00,4365.399902,4298.700195,4337.100098,True,False
2026-08-07 05:00:00-04:00,4399.700195,4365.399902,4298.700195,True,False
2026-08-09 17:00:00-04:00,4405.899902,4399.700195,4365.399902,True,False
2026-08-10 05:00:00-04:00,4448.600098,4405.899902,4399.700195,True,False
2026-08-10 17:00:00-04:00,4428.100098,4448.600098,4405.899902,False,True
2026-08-11 05:00:00-04:00,4427.799805,4428.100098,4448.600098,False,False
2026-08-11 17:00:00-04:00,4460.600098,4427.799805,4428.100098,True,False
2026-08-12 05:00:00-04:00,4469.000000,4460.600098,4427.799805,True,False
2026-08-12 17:00:00-04:00,4467.600098,4469.000000,4460.600098,False,True

In [12]:
datos_h12["Sobre_OURAS_C1"] = datos_h12["C1"] > datos_h12["OURAS"]
datos_h12["Sobre_OURAS_C2"] = datos_h12["C2"] > datos_h12["OURAS"]
datos_h12["Sobre_OURAS_C3"] = datos_h12["C3"] > datos_h12["OURAS"]

datos_h12["Conteo_sobre_OURAS"] = datos_h12["Sobre_OURAS_C1"].astype(int) + datos_h12["Sobre_OURAS_C2"].astype(int) + datos_h12["Sobre_OURAS_C3"].astype(int)

datos_h12["Sub_caso"] = "N/A"
datos_h12.loc[datos_h12["Conteo_sobre_OURAS"] == 3, "Sub_caso"] = "1_Limpio"
datos_h12.loc[datos_h12["Conteo_sobre_OURAS"] == 0, "Sub_caso"] = "2_Sin_cruzar"
datos_h12.loc[(datos_h12["Conteo_sobre_OURAS"] == 1) | (datos_h12["Conteo_sobre_OURAS"] == 2), "Sub_caso"] = "3_Cruzando"

datos_h12[["C1", "C2", "C3", "OURAS", "Conteo_sobre_OURAS", "Sub_caso"]].tail(10)

,C1,C2,C3,OURAS,Conteo_sobre_OURAS,Sub_caso
Datetime,,,,,,
2026-08-06 05:00:00-04:00,4298.700195,4337.100098,4308.000000,4337.100098,0,2_Sin_cruzar
2026-08-06 17:00:00-04:00,4365.399902,4298.700195,4337.100098,4337.100098,1,3_Cruzando
2026-08-07 05:00:00-04:00,4399.700195,4365.399902,4298.700195,4337.100098,2,3_Cruzando
2026-08-09 17:00:00-04:00,4405.899902,4399.700195,4365.399902,4337.100098,3,1_Limpio
2026-08-10 05:00:00-04:00,4448.600098,4405.899902,4399.700195,4337.100098,3,1_Limpio
2026-08-10 17:00:00-04:00,4428.100098,4448.600098,4405.899902,4446.899902,1,3_Cruzando
2026-08-11 05:00:00-04:00,4427.799805,4428.100098,4448.600098,4446.899902,1,3_Cruzando
2026-08-11 17:00:00-04:00,4460.600098,4427.799805,4428.100098,4446.899902,1,3_Cruzando
2026-08-12 05:00:00-04:00,4469.000000,4460.600098,4427.799805,4446.899902,2,3_Cruzando
2026-08-12 17:00:00-04:00,4467.600098,4469.000000,4460.600098,4468.100098,1,3_Cruzando

In [13]:
datos_h12.to_csv("../data/XAUUSD_h12_completo.csv")
print("Escenarios y Sub-casos guardados")

Escenarios y Sub-casos guardados